spring:
  application:
    name: Zero9-Platform

  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false #트랜잭션을 컨트롤러에서 끊고, 영속성 컨텍스트를 서비스까지만 열어두는 설정
    hibernate:
      ddl-auto: update
    properties:
      hibernate:

        #jdbc: # INSERT / UPDATE SQL을 1000개씩 묶어서 DB로 보낸다
        #  batch_size: 1000
        #order_inserts: true
        #order_updates: true

        format_sql: false
    show-sql: true

# Redis 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: ${REDIS_DB_RANKING}
      password: ${REDIS_PASSWORD}


# JWT 설정
jwt:
  secret:
    key: ${JWT_SECRET_KEY}

# S3 설정
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}